//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tema3MVVM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bon()
        {
            this.ProduseVandute = new HashSet<ProduseVandute>();
        }
    
        public long IDbon { get; set; }
        public System.DateTime data_eliberare { get; set; }
        public int IDcasier { get; set; }
        public float suma_incasata { get; set; }
        public bool exista { get; set; }
    
        public virtual Utilizator Utilizator { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProduseVandute> ProduseVandute { get; set; }
    }
}
