//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tema3MVVM
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProduseVandute
    {
        internal float pret;

        public long IDbon { get; set; }
        public long IDprodus { get; set; }
        public int cantitate { get; set; }
        public float subtotal { get; set; }
        public bool exista { get; set; }
    
        public virtual Bon Bon { get; set; }
        public virtual Produs Produs { get; set; }
    }
}
